/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/catalogo`; params?: Router.UnknownInputParams; } | { pathname: `/conversacion`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard-vendedor`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/faq`; params?: Router.UnknownInputParams; } | { pathname: `/favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/HistorialPedidos`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mensajes`; params?: Router.UnknownInputParams; } | { pathname: `/MiCatalogo`; params?: Router.UnknownInputParams; } | { pathname: `/MisVentas`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/publicar`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/soporte`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/editar-producto/[id_producto]`, params: Router.UnknownInputParams & { id_producto: string | number; } } | { pathname: `/producto/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/catalogo`; params?: Router.UnknownOutputParams; } | { pathname: `/conversacion`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard-vendedor`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/faq`; params?: Router.UnknownOutputParams; } | { pathname: `/favoritos`; params?: Router.UnknownOutputParams; } | { pathname: `/HistorialPedidos`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/mensajes`; params?: Router.UnknownOutputParams; } | { pathname: `/MiCatalogo`; params?: Router.UnknownOutputParams; } | { pathname: `/MisVentas`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/publicar`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/soporte`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/editar-producto/[id_producto]`, params: Router.UnknownOutputParams & { id_producto: string; } } | { pathname: `/producto/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/catalogo${`?${string}` | `#${string}` | ''}` | `/conversacion${`?${string}` | `#${string}` | ''}` | `/dashboard-vendedor${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/faq${`?${string}` | `#${string}` | ''}` | `/favoritos${`?${string}` | `#${string}` | ''}` | `/HistorialPedidos${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/mensajes${`?${string}` | `#${string}` | ''}` | `/MiCatalogo${`?${string}` | `#${string}` | ''}` | `/MisVentas${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `/publicar${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/soporte${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/catalogo`; params?: Router.UnknownInputParams; } | { pathname: `/conversacion`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard-vendedor`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/faq`; params?: Router.UnknownInputParams; } | { pathname: `/favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/HistorialPedidos`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mensajes`; params?: Router.UnknownInputParams; } | { pathname: `/MiCatalogo`; params?: Router.UnknownInputParams; } | { pathname: `/MisVentas`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/publicar`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/soporte`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/editar-producto/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/producto/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/editar-producto/[id_producto]`, params: Router.UnknownInputParams & { id_producto: string | number; } } | { pathname: `/producto/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
